/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karen
 */
public class jF_spelerZoeken extends javax.swing.JFrame {

    boolean eersteKeer = true;

    /**
     * Creates new form jF_evenementZoeken
     */
    public jF_spelerZoeken() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/pokerSpade.png")).getImage());
        this.getContentPane().setBackground(Color.white);
        vulSpelersTabel();
    }

    private void vulSpelersTabel() {
        try {
            DefaultTableModel datamodel = createVoedingModel();
            this.jT_spelerZoeken.setModel(datamodel);

            String query = "select spelernr, s_naam, s_ranking from Speler "
                    + "where s_naam like ?;";
            Connection connection = FullhouseDB.getConnection();
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, getZoekTerm());

            ResultSet results = statement.executeQuery();

            while (results.next()) {
                int spelernr = results.getInt("SpelerNr");
                String spelerNaam = results.getString("s_naam");
                int ranking = results.getInt("s_ranking");
                Object[] rij = {new Integer(spelernr), spelerNaam, ranking};
                // Object[row][column]
                datamodel.addRow(rij);

            }
            this.jT_spelerZoeken.setModel(datamodel);
        } catch (SQLException ex) {
            Logger.getLogger(jF_spelerZoeken.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private String getZoekTerm() {
        String text = Tf_zoekterm.getText();
        if (eersteKeer || text.length() == 0) {
            return "%";
        } else {
            return "%" + text + "%";
        }
    }

    private DefaultTableModel createVoedingModel() {
        DefaultTableModel model = new TableModel();
        model.addColumn("SpelerNr.");
        model.addColumn("Naam");
        model.addColumn("Ranking");
        return model;
    }

    class TableModel extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tf_zoekterm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_spelerZoeken = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tf_zoekterm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tf_zoektermFocusGained(evt);
            }
        });
        Tf_zoekterm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tf_zoektermKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SPELER ZOEKEN");

        jLabel2.setText("Speler naam:");

        jT_spelerZoeken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_spelerZoeken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jT_spelerZoekenMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_spelerZoeken);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tf_zoekterm))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_zoekterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf_zoektermFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tf_zoektermFocusGained
        if (eersteKeer) {
            Tf_zoekterm.setText("");
            eersteKeer = false;

        }
    }//GEN-LAST:event_Tf_zoektermFocusGained

    private void Tf_zoektermKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_zoektermKeyReleased
        this.vulSpelersTabel();
    }//GEN-LAST:event_Tf_zoektermKeyReleased

    private void jT_spelerZoekenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_spelerZoekenMousePressed
        if (evt.getClickCount() == 2) {
            int rij = this.jT_spelerZoeken.getSelectedRow();
            if (rij > -1) {
                int voednr = (Integer) jT_spelerZoeken.getValueAt(rij, 0);
                this.setVisible(false);
                Jf_indeling event = new Jf_indeling(voednr);
                event.setVisible(true);
            }
        }
    }//GEN-LAST:event_jT_spelerZoekenMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jF_spelerZoeken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jF_spelerZoeken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jF_spelerZoeken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jF_spelerZoeken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jF_spelerZoeken().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tf_zoekterm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_spelerZoeken;
    // End of variables declaration//GEN-END:variables
}
